ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

WORKDIR /app

COPY backend-services /tmp/backend-services

RUN pip install --upgrade pip \
    && pip install -r /tmp/backend-services/user-service/requirements.txt

COPY backend-services/user-service/app /app/app
COPY backend-services/user-service/alembic.ini /app/alembic.ini
COPY backend-services/user-service/alembic /app/alembic

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
